export const vectors = {
  backward: require('./backward.svg'),
  jejeup: require('./jejeup.svg'),
  play: require('./play.svg'),
  share: require('./share.svg'),
  share2: require('./share2.svg'),
  more: require('./more.svg'),
  ott: {
    amazon: require('./ott/amazon.svg'),
    amazon2: require('./ott/amazon2.svg'),
    amazonIcon: require('./ott/amazon-icon.svg'),
    apple: require('./ott/apple.svg'),
    apple2: require('./ott/apple2.svg'),
    appleIcon: require('./ott/apple-icon.svg'),
    disney: require('./ott/disney.svg'),
    disney2: require('./ott/disney2.svg'),
    disneyIcon: require('./ott/disney-icon.svg'),
    netflix: require('./ott/netflix.svg'),
    netflixIcon: require('./ott/netflix-icon.svg'),
    tvingIcon: require('./ott/tving-icon.svg'),
    tvingOnly: require('./ott/tving-only.svg'),
    tvingOrigin: require('./ott/tving-original.svg'),
    tvingOnly2: require('./ott/tving-only2.svg'),
    tvingOrigin2: require('./ott/tving-original2.svg'),
    watchaIcon: require('./ott/watcha-icon.svg'),
    watchaOnly: require('./ott/watcha-only.svg'),
    watchaOrigin: require('./ott/watcha-original.svg'),
    watchaOnly2: require('./ott/watcha-only2.svg'),
    watchaOrigin2: require('./ott/watcha-original2.svg'),
    wavveIcon: require('./ott/wavve-icon.svg'),
    wavveOnly: require('./ott/wavve-only.svg'),
    wavveOrigin: require('./ott/wavve-original.svg'),
    wavveOnly2: require('./ott/wavve-only2.svg'),
    wavveOrigin2: require('./ott/wavve-original2.svg'),
    paramountIcon: require('./ott/paramount-icon.svg'),
    paramount: require('./ott/paramount.svg'),
  },
  ratings: {
    film: {
      all: require('./ratings/film/all.svg'),
      b12: require('./ratings/film/b12.svg'),
      c15: require('./ratings/film/c15.svg'),
      d18: require('./ratings/film/d18.svg'),
    },
    game: {
      all: require('./ratings/game/all.svg'),
      b12: require('./ratings/game/b12.svg'),
      c15: require('./ratings/game/c15.svg'),
      d19: require('./ratings/game/d19.svg'),
    },
  },
};
